/*
 *  Copyright (c) 2015, FeeManagement and/or its affiliates. All rights reserved.
 */
package com.feemanagement.frontend;

import com.feemanagement.dto.PaymentDetails;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author 786
 */
public class PaymentDetailFrontEnd extends javax.swing.JDialog {

    String pattern = "^[0-9]*$";
    Pattern r = Pattern.compile(pattern);

    /**
     * Creates new form PaymentDetailFrontEnd
     *
     * @param parent
     * @param modal
     */
    public PaymentDetailFrontEnd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * \This method reset the payment detail field
     */
    public void resetPaymentDetailForm() {
        bankNameField.setText("");
        accountNumberField.setText("");
        chequeNumberField.setText("");
        tellerNumberField.setText("");
        pinField.setText("");
    }

    /**
     * get and validate the value of the payment detail form
     *
     * @return
     */
    public boolean validatePaymentDetailForm() {

        boolean result = false;
        if (bankNameField.getText() != null && accountNumberField.getText() != null && chequeNumberField.getText() != null && tellerNumberField.getText() != null && pinField.getText() != null && bankNameField.getText().trim().length() > 0 && accountNumberField.getText().trim().length() > 0 && chequeNumberField.getText().trim().length() > 0 && tellerNumberField.getText().trim().length() > 0 && pinField.getText().trim().length() > 0) {
            if (r.matcher((accountNumberField.getText())).matches()) {

                if (r.matcher((tellerNumberField.getText())).matches()) {

                    if (r.matcher((pinField.getText())).matches()) {
                        result = true;

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Pin must be number  ", "Number formet eror", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Teller number must be number  ", "Number formet eror", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Account number must be number  ", "Number formet eror", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Please Supply all the value ", "Empty field variable", JOptionPane.ERROR_MESSAGE);
        }

        return result;
    }

    /**
     *
     * @return
     */
    public PaymentDetails getValueFromPaymentDetailform() {
        PaymentDetails paymentDetails = null;
        if (validatePaymentDetailForm()) {
            paymentDetails = new PaymentDetails();
            paymentDetails.setBankName(bankNameField.getText());
            paymentDetails.setAccountNumber(Integer.parseInt(accountNumberField.getText()));
            paymentDetails.setChequeNumber(chequeNumberField.getText());
            paymentDetails.setTellerNumber(Integer.parseInt(tellerNumberField.getText()));
            paymentDetails.setPinNumber(Integer.parseInt(pinField.getText()));
        }
        return paymentDetails;
    }

    /**
     * method save the payment form detail in to the database
     */
    public void savePaymentDetails() {
        PaymentDetails paymentDetails = getValueFromPaymentDetailform();
        if (paymentDetails != null) {
            PayFeeFrontEnd.paymentDetails123 = paymentDetails;
            JOptionPane.showMessageDialog(rootPane, "Payment detail add sucessfully", "Response", JOptionPane.INFORMATION_MESSAGE);
//        Response response=new PaymentDetailServiceImpl().savePaymentDetail(paymentDetails);
//        if(response.getStatus()==1)
//        {
//        JOptionPane.showMessageDialog(rootPane,response.getMessage(), "Response",JOptionPane.INFORMATION_MESSAGE);
//        PayFeeFrontEnd.paymentModeId=(Integer)response.getData();
//            System.out.println("payment max id  "+ response.getData());
//        }
//        else{
//            JOptionPane.showMessageDialog(rootPane,response.getMessage(), "Response",JOptionPane.ERROR_MESSAGE);
//        }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bankNameField = new javax.swing.JTextField();
        accountNumberField = new javax.swing.JTextField();
        chequeNumberField = new javax.swing.JTextField();
        tellerNumberField = new javax.swing.JTextField();
        pinField = new javax.swing.JTextField();
        savepaymentDetail = new javax.swing.JButton();
        resetPaymentForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Detail Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 2, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N
        jLabel1.setText("Bank Name");

        jLabel2.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N
        jLabel2.setText("Account Number ");

        jLabel3.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N
        jLabel3.setText("Cheque / DD Number ");

        jLabel4.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N
        jLabel4.setText("Teller Number ");

        jLabel5.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N
        jLabel5.setText("Pin");

        savepaymentDetail.setText("Save");
        savepaymentDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savepaymentDetailActionPerformed(evt);
            }
        });

        resetPaymentForm.setText("Reset");
        resetPaymentForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPaymentFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(7, 7, 7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(accountNumberField)
                    .addComponent(chequeNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tellerNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(savepaymentDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetPaymentForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {accountNumberField, bankNameField, chequeNumberField, pinField, tellerNumberField});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bankNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(accountNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chequeNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tellerNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savepaymentDetail)
                    .addComponent(resetPaymentForm))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetPaymentFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPaymentFormActionPerformed
        resetPaymentDetailForm();
    }//GEN-LAST:event_resetPaymentFormActionPerformed

    private void savepaymentDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savepaymentDetailActionPerformed
        savePaymentDetails();
    }//GEN-LAST:event_savepaymentDetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentDetailFrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentDetailFrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentDetailFrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentDetailFrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                PaymentDetailFrontEnd dialog = new PaymentDetailFrontEnd(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumberField;
    private javax.swing.JTextField bankNameField;
    private javax.swing.JTextField chequeNumberField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField pinField;
    private javax.swing.JButton resetPaymentForm;
    private javax.swing.JButton savepaymentDetail;
    private javax.swing.JTextField tellerNumberField;
    // End of variables declaration//GEN-END:variables
}
